Already-Locking: "<red>Je bent al een lock aan het maken."
Already-Unlocking: "<red>Je bent al een block aan het unlocken."
Create-Lock: "<green>Klik rechtermuisknop op een block om een lock aan te maken."
Delete-Lock: "<green>Klik rechtermuisknop op een block dat je wilt unlocken."
Unlockable-Block: "<red>Dit is geen lockable block."
No-Lock: "<red>Er staat geen lock op dit block."
No-Owner: "<red>Je bent niet de owner van deze lock."
No-Member: "<red>Deze speler is geen member van deze lock."
Already-Member: "<red>Deze speler is al een member van deze lock."
Player-Added: "<green>Je hebt <dark_green>%player% <green>toegevoegd aan de lock."
Removed-Member: "<green>Je hebt <dark_green>%player% <green>verwijderd van de lock."
Set-Owner-Lock: "<green>Je hebt <dark_green>%player% <green>de owner gemaakt van deze lock."
Lock-Break: "<green>De lock van het gesloopte block is verwijderd."
No-Lock-Possible: "<red>Je kan hier geen lock plaatsen."
Already-Lock: "<red>Dit block is al gelocked."
Lock-Created: "<green>Lock aangemaakt."
Cant-Delete: "<red>Je kan hier geen lock deleten."
Lock-Deleted: "<green>Lock verwijderd."
Not-Member: "<red>Je staat niet op deze lock."
Lock-Opening-Staff: "<green>Je opent een gelocked block van <dark_green>%player%."
Lock-Opening: "<green>Je opent een gelocked block."